services:
  web:
    build: .
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=security_exercise

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: security_exercise
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  attacker:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./attacker:/var/www/html
    environment:
      - SITE_TYPE=attacker